org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
kotlin.code.style=official
kotlin.incremental=true
kotlin.daemon.jvm.options=-Xmx2

modId=safesquares
modVersion=1.1.0
mavenGroup=sh.lem.safesquares
archivesBaseName=safesquares
gitRepo=Lemmmy/SafeSquares
